export { default as apl } from "../public/apl-logo.svg";
export { default as fb } from "../public/fb-logo.svg";
export { default as ll } from "../public/lincoln-lab-logo.svg";
export { default as logo } from "../public/logo.svg";
export { default as meta } from "../public/meta-logo.svg";
export { default as umich } from "../public/umich-logo.svg";
export { default as upwork } from "../public/upwork-logo.svg";
export { default as washu } from "../public/washu-logo.svg";
export { default as yelp } from "../public/yelp-logo.svg";
